New strategy for detecting build failures: look for presense of temp file only cleaned up by build script if no errors

diff --git a/.github/workflows/build-deb-v4.yml b/.github/workflows/build-deb-v4.yml
--- a/.github/workflows/build-deb-v4.yml
+++ b/.github/workflows/build-deb-v4.yml
@@ -176,11 +176,12 @@ jobs:
             ${{ steps.init.outputs.MANIFEST_PATH }} \
             ${{ steps.init.outputs.PKG_REPO_PATH }} \
             ${{ steps.init.outputs.PKG_BUILD_DIR }} | tee -a ${{ steps.init.outputs.GH_REPO_ROOT }}/CHANGELOG_${{ steps.init.outputs.target }}.raw.txt
-          if [ -s "${{ steps.init.outputs.PKG_REPO_PATH }}/manifest.txt" ]; then
-            cat ${{ steps.init.outputs.GH_REPO_ROOT }}/CHANGELOG_${{ steps.init.outputs.target }}.raw.txt | grep ^CHLOG: | cut -c 7- > ${{ steps.init.outputs.GH_REPO_ROOT }}/CHANGELOG_${{ steps.init.outputs.target }}.txt
+          if [ -f ${{ steps.init.outputs.MANIFEST_PATH }}/next-manifest.txt ]; then
+            echo "Temp manifest not deleted by main.sh, build aborted/failed."
+            echo ::set-output name=changed::0
+            exit 1            
           else
-            echo "Manifest is empty, build failed"
-            exit 1
+            cat ${{ steps.init.outputs.GH_REPO_ROOT }}/CHANGELOG_${{ steps.init.outputs.target }}.raw.txt | grep ^CHLOG: | cut -c 7- > ${{ steps.init.outputs.GH_REPO_ROOT }}/CHANGELOG_${{ steps.init.outputs.target }}.txt
           fi
       - name: Deploy via rsync
         if: steps.changes.outputs.changed == 1
